name: Build-Ubuntu-24.04

on:
  push:
  pull_request:
  merge_group:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: >-
          sudo apt-get update

          sudo apt-get install -y
          build-essential
          g++
          qt6-base-dev
          qt6-l10n-tools
          qt6-multimedia-dev
          qt6-tools-dev-tools
          qt6-tools-dev
          qmake6
          libqt6multimedia6
          libqt6serialport6-dev
          linguist-qt6
          libhamlib-dev
          libv4l-dev
          libfftw3-dev
          libasound2-dev
          libopenjp2-7-dev
          libpulse-dev
          libgl-dev
      - name: Run Qmake
        run: >-
          mkdir src/build;
          cd src/build;
          qmake6  ../qsstv.pro
      - name: Build
        run: >-
          cd src/build;
          make
      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-x86_64
          path: |
            src/build/
            !**/*.d
            !**/*.o
      - name: Archive executables
        uses: actions/upload-artifact@v4
        with:
          name: qsstv-linux-x86_64
          path: |
            src/build/qsstv
